language: python
env:
  global:
  - PROJECT_NAME=tinycov
  - GITHUB_REPO_NAME=cmdoret/tinycov
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
os:
- linux
install:
- pip install -v -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage tests/test_tinycov.py
after_success:
- codecov
deploy:
  on:
    branch: master
    tags: true
  provider: pypi
  skip_existing: true
  user: cmdoret
  password:
    secure: Y0drjoAO/U+e2wa7bQ9YlgXTOi6X9vIXkKqFd1UtpeL2S1jbmAztZBHCIOeO0yKuGiMZ9WZcTQQF3HM5/BUYgNKxaAvFj16sppW8Le/HVZ+r2QsLU8jb22JcHUI6PftIgdnOJG5WKw0OHMDF164zYF53um3dRQ3OCgYdRcGlAUrOKdoPaYzynkpMb/2oZeNkyQTFBEiGPV3HiC8yHuI2ZOuuzN4GDHXz+teZpu8uhLeStunX21EH4A9npEILCEat2uvx25q2TST/OlZK5+nGhOVBt7XnOpIJYDYEYkrV2pcmwmW6EQwxVxz+oR31TyuiBXupKpSMCI2AihZZHNg6g0dy/ZJf9GugIC1hDaCdfZWdF+zmw/qf9DD2Hxg2Ya444kWE+AxVvw+VIxf4bnDqrdkS7WxRRnMtqT0QUIH2omy3ghLIkm8TjKjcORt+63jiVXlsv0+ug5cRsGC37M117CemJboVion85rPEYrVvbiHwdS/l9uX5Fz868S7Rh+6EofH8Kt/nL/wvsc1znsDgfmuTcrimJljKYNY5fQNJvTVqtomv4Nxdwwt5BGSdDbPpyH2xoPpNIsEBDq8lSYaH5pxv5txCY36c3x9hO+38D6rkAdV+/eVrSEuq1MwTERR71W0l0JAaDm25/N3hWOtYCM1pCq71v4CnPA3GyTz5t24=
  distributions: sdist bdist_wheel
