language: python
env:
  global:
  - PROJECT_NAME=tinycov
  - GITHUB_REPO_NAME=cmdoret/tinycov
matrix:
  include:
  - python: '3.6'
  - python: '3.7'
    dist: xenial
    sudo: true
os:
- linux
install:
- pip install -v -r requirements.txt
- pip install codecov
script:
- nosetests --with-coverage tests/test_tinycov.py
after_success:
- codecov
deploy:
  on:
    branch: master
    tags: true
  provider: pypi
  skip_existing: true
  user: cmdoret
  password:
    secure: JEwI185k27GlkN8SnBGR6eFZ7uwTT9xxNKfi9Ajzpe88hSBEZOusfGFXGtBUHhkktNKxzyy3xzXgMjtTcpl9zeFdjFHGF8L+1F6RZq3L6bVOotppHQzPiJtxF/3HkWxJxKu7ISpjykPvK8Oplg28pdRrXa+L6PXG3InIq+BOtOfj644P8clJKi/n6B30dldgZcWfIhYwaq6VErDKmUU9KULhFO9V6imMipL4xnPve9Pb82xOyCMOlki8QyPVtda148cXBFD1w5IUqzqWRcAIjr7QP3UfirEtXJVGFKPcKzkwjHFPqpM24qlBcHhnTdyvZAgj4IITmIOyAoh88p8p74TRULbKEOe4xU7g7N6YvQCAeAuERsn6lIVqdRm3Ui9gc/ouai3xqFdSPKEi1yrd2e+t2iai8t9eGdprqOecHriLWseNpK9gchC49kTcvXUVpOS7Zs8bR1ceRt12e+A8pD+dRYp2QH/irmHTBZcgraWbk+HsCPaYy2LNYWO8o42nTQE0GXZY3XoQPLUPU/sguNQMVJQWJiD6CnitEZLhf1nWeN+BLaNE3xvy81tFCQjfegm6bPc/BvZ0LGHoAjiJXypd3BvWkKc7Iqr9oCG78o5OHAcwcVnl8nKIELPJQY5jaVpal6wBdA9kSSNzG0NNVOFRuRn0zakwkPAiWYnL/bs=
  distributions: sdist bdist_wheel
